from . import dental_patient
from . import dental_doctor
from . import dental_staff
from . import dental_attendance
from . import dental_appointment
from . import dental_treatment
from . import dental_tooth
from . import dental_service
from . import dental_prescription
from . import dental_xray
from . import dental_inventory
