from . import patient
from . import doctor
from . import appointment
from . import prescription
from . import inventory
from . import department
from . import shift
from . import staff
from . import attendance
from . import leave
from . import service
from . import bill