{
    'name': 'Hospital Management',
    'version': '19.0.1.0.0',
    'summary': 'Manage Patients, Doctors, and Appointments',
    'description': 'Full Hospital Management System - Patients, Doctors, Appointments',
    'author': 'Bilal Shahzad',
    'Price': '50.0',
    'Currency': 'USD',
    'category': 'Healthcare',
    'depends': ['base', 'mail', 'portal', 'sale', 'stock', 'account', 'appointment'],
    'data': [
        'data/sequence.xml',
        'data/appointment_type.xml',
        'views/patient_views.xml',
        'views/doctor_views.xml',
        'views/appointment_views.xml',
        'views/prescription_views.xml',
        'views/inventory_views.xml',
        "views/department_views.xml",
        "views/shift_views.xml",
        "views/staff_views.xml",
        "views/attendance_views.xml",
        "views/leave_views.xml",
        "views/service_views.xml",
        "views/bill_views.xml",
        "views/dashboard.xml",
        # 'views/hospital_dashboard_sidebar.xml',
        'views/portal_templates.xml',
        'views/menu.xml',
        "report/bill_report.xml",
        'report/prescription_report.xml',
        'report/prescription_report_action.xml',
        'security/ir.model.access.csv',
    ],
    'images': ['static/description/icon.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
