{
    'name': 'Dental Clinic',
    'version': '19.0.1.0.0',
    'summary': 'Complete Dental Clinic Management System',
    'description': 'Manage Patients, Appointments, Treatments, Tooth Charts, Prescriptions, X-Rays, Inventory and Invoicing for a dental clinic.',
    'author': 'Bilal Shahzad',
    'category': 'Healthcare',
    'depends': ['base', 'mail', 'account', 'appointment', 'product', 'hr', 'hr_attendance', 'stock', 'uom'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/appointment_type.xml',
        'data/tooth_surfaces.xml',
        'data/dental_services.xml',
        'data/dental_inventory_products.xml',
        'views/dental_patient_views.xml',
        'views/dental_doctor_views.xml',
        'views/dental_appointment_views.xml',
        'views/dental_treatment_views.xml',
        'views/dental_service_views.xml',
        'views/dental_prescription_views.xml',
        'views/dental_xray_views.xml',
        'views/dental_staff_views.xml',
        'views/dental_attendance_views.xml',
        'views/dental_inventory_views.xml',
        'views/menu.xml',
    ],
    'images': ['static/description/icon.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
